src/Entity/Orderlouvre.php
<?php

namespace App\Entity;

use App\Validator\After14;
use App\Validator\BillNotNull;
use App\Validator\SundaysAndHolidays;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrderlouvreRepository")
 */
class Orderlouvre
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *     min=2       ,
     *     max=20 ,
     *     minMessage="Trop court , vous devez rentrer au moins {{ limit }} caractères",
     *     maxMessage="Trop long"
     * )
     * @Assert\NotBlank()
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=2       ,
     *      max=20 ,
     *      minMessage="Trop court , vous devez rentrer au moins {{ limit }} caractères",
     *      maxMessage="Trop long")
     * @Assert\NotBlank()
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email()
     * @Assert\NotBlank()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Country()
     * @Assert\NotBlank()
     */
    private $country;
    

    /**
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\TicketLouvre",
     *      mappedBy="OrderLouvre",
     *      orphanRemoval=true ,
     *      cascade="all"
     * )
     *
     * @Assert\Valid()
     * @BillNotNull()
     */
    private $ticketLouvre;


    /**
     * @ORM\Column(type="datetime")
     */
    private $dateOrder;

    /**
     *
     * @ORM\Column(type="string", length=255)
     */
    private $reference;







    public function __construct()
    {
        $this->ticketLouvre = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getTotalPrice()
    {
        $price=0;

        foreach ($this->getTicketLouvre() as $ticket) {
            $price+=$ticket->getTicketPrice();
        }

        return $price;
    }





    public function getTicketNumber(): ?int
    {
        return $this->ticketNumber;
    }

    public function setTicketNumber(int $ticketNumber): self
    {
        $this->ticketNumber = $ticketNumber;

        return $this;
    }

    /**
     * @return Collection|TicketLouvre[]
     */
    public function getTicketLouvre(): Collection
    {
        return $this->ticketLouvre;
    }

    public function addTicketLouvre(TicketLouvre $ticketLouvre): self
    {
        if (!$this->ticketLouvre->contains($ticketLouvre)) {
            $this->ticketLouvre[] = $ticketLouvre;
            $ticketLouvre->setOrderLouvre($this);
        }

        return $this;
    }

    public function removeTicketLouvre(TicketLouvre $ticketLouvre): self
    {
        if ($this->ticketLouvre->contains($ticketLouvre)) {
            $this->ticketLouvre->removeElement($ticketLouvre);
            // set the owning side to null (unless already changed)
            if ($ticketLouvre->getOrderLouvre() === $this) {
                $ticketLouvre->setOrderLouvre(null);
            }
        }

        return $this;
    }

    public function getDateOrder(): ?\DateTimeInterface
    {
        return $this->dateOrder;
    }

    public function setDateOrder(\DateTimeInterface $dateOrder): self
    {
        $this->dateOrder = $dateOrder;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }
}

src/Controller/ViewRecapOrderController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ViewRecapOrderController extends AbstractController
{
    /**
     * @Route("/view/recap/order", name="view_recap_order")
     */
    public function index()
    {
        /* @var array */
        $tickets=$this->get('session')->get('order')->getTicketLouvre();

        return $this->render(
            'view_recap_order/index.html.twig',
            [
            'controller_name' => 'ViewRecapOrderController',
                'tickets' => $tickets
            ]
        );
    }
}

templates/view_recap_order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}

    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
        .recap {
            border: 1px solid black;
            font-size:1em;
            font-weight:bold;
            padding:10px;
            background-color: lightgray;}
        p.recap {font-size: 1em;
            background-color: #AA3333;}
        fieldset.form-group legend.col-form-label.required {display:none;}
        .comment { font-style: italic}
        .centeredblock{text-align:center;}
    </style>

<div class="recap">

    <h2 class="centeredblock">Voici un récapitulatif de votre commande</h2>

    {% for ticket in tickets %}

        <p>Nom : {{ticket.LastName }}</p>
        <p>Prenom : {{ticket.FirstName}}</p>

        {%  if ticket.HalfDay %}
            <p>Tarif demi journée</p>
        {% endif %}

        {%  if ticket.ReducedRate %}
            <p>Tarif réduit</p>
            <p class="comment">( Pensez à présenter votre justificatif le jour de la visite ) </p>
        {% endif %}

        <p>Date de visite : {{ticket.DateTicket|date('d/m/Y')}}</p>
        <hr/>

    {%  endfor %}
        <p>Montant total : {{ app.session.get('order').totalPrice }} euros </p>



    <form action={{ path('payment_validation') }} method="POST" class="centeredblock">
        <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="pk_test_HAIzVTbXuDr9O7TXd345a9Xn"
                data-amount={{ app.session.get('orderPrice')*100}},
                data-label="Payer par carte"
                data-currency='EUR'
                data-name="Louvre"
                data-description="Widget"
                data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                data-locale="auto">
        </script>
    </form>








</div>
{% endblock %}